// Banque de questions - Questions pour un Giant
const QUIZ_QUESTIONS = [
  // ===== COMPOSITION DES BURGERS =====
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger contient une sauce tartare ?", choices:["Giant","Long Fish","Suprême Classiq","Cheeseburger"], answer:1},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger est composé de : bun blanc, ketchup, moutarde, cheddar, 1 patty ?", choices:["Cheeseburger","Giant","Long Bacon","Suprême Classiq"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quel ingrédient retrouve-t-on dans presque tous les burgers pour apporter du croquant ?", choices:["Tomate","Cornichon","Oignons rouges","Iceberg/scarole"], answer:3},
  {cat:"Composition des burgers", diff:"facile", q:"Le Long Bacon contient du bacon de quelle viande ?", choices:["Bœuf","Porc","Poulet","Dinde"], answer:2},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger utilise un bun toast ?", choices:["Quick'N Toast","Giant Max","Long Fish","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quelle sauce accompagne le Giant ?", choices:["Sauce tartare","Sauce giant","Sauce chicken cheese","Sauce oignon poivre"], answer:1},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger est composé de : bun long, sauce tartare, iceberg, 1 patty poisson ?", choices:["Long Fish","Long Chicken","Suprême Classiq","Giant"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger est composé de : bun long, sauce chicken cheese, iceberg, 1 patty poulet long ?", choices:["Long Chicken","Long Fish","Suprême Spicy Chicken","Quick'N Toast"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger est la version « mini » de la gamme Giant ?", choices:["Junior Giant","Giant Max","Méga Giant","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger végétarien existe dans la gamme wrap ?", choices:["Wrap Cheese & Bacon","Wrap Giant Veggie","Long Fish","Cheeseburger"], answer:1},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger utilise une tortilla à la place d'un bun ?", choices:["Wrap Cheese & Bacon","Long Chicken","Suprême Bacon","Quick'N Toast"], answer:0},
  {cat:"Composition des burgers", diff:"facile", q:"Quel burger contient 2 patty et 2 tranches de cheddar ?", choices:["Double Cheese","Giant Max","Méga Giant","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quelle quantité de sauce giant est utilisée dans le Giant Max ?", choices:["10g","20g","30g","40g"], answer:2},
  {cat:"Composition des burgers", diff:"moyenne", q:"Le Suprême Spicy Chicken contient quelle sauce ?", choices:["Sauce chicken cheese","Sauce very hot","Sauce goût fumé","Sauce oignon poivre"], answer:1},
  {cat:"Composition des burgers", diff:"moyenne", q:"Combien de patty compose le Méga Giant ?", choices:["1","2","3","4"], answer:1},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel ingrédient est spécifique au Suprême Bacon parmi ces choix ?", choices:["Cornichons","Oignons frits","Emmental à trous","Bacon de poulet + cheddar"], answer:3},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient des cornichons ?", choices:["Cheeseburger","Giant","Long Fish","Suprême Classiq"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger de la gamme ClassiQ contient des oignons frits ?", choices:["ClassiQ Crispy Onion Beef","ClassiQ Spicy Beef","Suprême Classiq","Giant Max"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient une sauce goût fumé ?", choices:["Long Bacon","Long Fish","Giant","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient à la fois oignons rouges ET oignons en dés ?", choices:["Wrap Cheese & Bacon","Suprême Classiq","Aucun burger de la gamme","Giant Max"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient à la fois moutarde ET ketchup ?", choices:["Cheeseburger","Giant","Long Fish","Suprême Classiq"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient un patty poisson ?", choices:["Long Fish","Long Chicken","Suprême Spicy Chicken","Giant Max"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger contient un patty veggie ?", choices:["Wrap Giant Veggie","Long Bacon","Suprême Classiq","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"moyenne", q:"Quel burger utilise un bun suprême ?", choices:["Suprême Classiq","Cheeseburger","Long Fish","Giant"], answer:0},
  {cat:"Composition des burgers", diff:"difficile", q:"Quel burger est composé de : bun toast, sauce goût fumé, cheddar, bacon de poulet, 1 patty ?", choices:["Quick'N Toast","Suprême Bacon","Long Bacon","Giant Max"], answer:0},
  {cat:"Composition des burgers", diff:"difficile", q:"Quel burger est composé de : bun suprême, sauce sup. classiq, scarole/roquette, oignons rouges, tomates, cheddar, 1 patty medium ?", choices:["Suprême Classiq","Giant Max","Méga Giant","Long Bacon"], answer:0},
  {cat:"Composition des burgers", diff:"difficile", q:"Combien de grammes de scarole lanière sont utilisés dans le Giant ?", choices:["10g","15g","20g","25g"], answer:1},
  {cat:"Composition des burgers", diff:"difficile", q:"Quelle est la quantité de mix sel/poivre utilisée sur un burger avec patty Large (type Méga Giant) ?", choices:["0,5g","1g","1,5g","2g"], answer:1},
  {cat:"Composition des burgers", diff:"difficile", q:"Quel burger contient de l'emmental à trous ?", choices:["Suprême Classiq","Giant","Long Fish","Cheeseburger"], answer:0},
  {cat:"Composition des burgers", diff:"difficile", q:"Quel burger est composé de : bun long, sauce goût fumé, cheddar, bacon de poulet, 1 patty ?", choices:["Long Bacon","Quick'N Toast","Suprême Bacon","Giant Max"], answer:0},

  // ===== SECURITE ALIMENTAIRE & HYGIENE =====
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"Que signifie HACCP ?", choices:["Hazard Analysis of Critical Control Point","Hygiène Alimentaire des Chaînes de Contrôle Professionnel","Haute Autorité de Contrôle et Conformité Produits","Hygiène Automatique et Contrôle Continu des Process"], answer:0},
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"À quelle fréquence minimum doit-on se laver les mains ?", choices:["Toutes les 30 minutes","Toutes les 60 minutes","Toutes les 2 heures","Une fois par service"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"Que signifie FIFO ?", choices:["First In First Out","Food Inventory Follow-up","Fresh Ingredients First Order","First Inspection First Output"], answer:0},
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"La charlotte doit recouvrir quelles parties ?", choices:["Uniquement le sommet du crâne","Le front et les oreilles","Uniquement l'arrière de la tête","Les cheveux longs uniquement"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"Combien de temps minimum doit-on frotter les mains avec le savon bactéricide ?", choices:["10 secondes","20 secondes","30 secondes","60 secondes"], answer:2},
  {cat:"Sécurité alimentaire & hygiène", diff:"facile", q:"Un burger servi à un client peut-il revenir dans le bin ?", choices:["Oui, si non entamé","Non, jamais","Oui, avec l'accord du manager","Oui, s'il est reconditionné"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Quelle couleur de zone correspond aux sanitaires clients et personnel ?", choices:["Zone Blanche","Zone Bleue","Zone Verte","Zone Rouge"], answer:3},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Quelle couleur de zone correspond à la zone de production (grill, frites, salades) ?", choices:["Zone Blanche","Zone Bleue","Zone Verte","Zone Rouge"], answer:2},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Qu'est-ce que la DLC secondaire (code Quick) ?", choices:["Une date préférentielle facultative","Un code attribué quand l'emballage est entamé/déconditionné","La date de fabrication du produit","Un code réservé aux viandes uniquement"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Quel principe garantit qu'un produit suit un chemin sans retour en arrière ?", choices:["La sectorisation","La marche en avant","Le FIFO","Le TACT"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Une surface visuellement propre est-elle forcément propre bactériologiquement ?", choices:["Oui, toujours","Non, une surface propre visuellement peut contenir des bactéries","Oui, si elle a été rincée","Non, sauf en zone verte"], answer:1},
  {cat:"Sécurité alimentaire & hygiène", diff:"moyenne", q:"Que veut dire « décartonner » une matière première ?", choices:["La jeter","Retirer l'emballage primaire","La transvaser en gastronorme","Retirer l'emballage carton (secondaire)"], answer:3},
  {cat:"Sécurité alimentaire & hygiène", diff:"difficile", q:"Quel est le pourcentage de composés polaires maximum toléré pour conserver une huile de friture ?", choices:["15%","18%","22%","25%"], answer:2},
  {cat:"Sécurité alimentaire & hygiène", diff:"difficile", q:"Combien de temps l'huile de friture peut-elle être utilisée au maximum, tous modèles de friteuses confondus ?", choices:["14 jours","21 jours","28 jours","35 jours"], answer:2},
  {cat:"Sécurité alimentaire & hygiène", diff:"difficile", q:"Lors d'une désinfection approfondie au Kay 5, quelle concentration minimum en chlore doit être vérifiée avec le testeur ?", choices:["50 ppm","75 ppm","100 ppm","150 ppm"], answer:2},

  // ===== PRODUITS D'ENTRETIEN =====
  {cat:"Produits d'entretien", diff:"facile", q:"Peut-on mélanger deux produits d'entretien différents ?", choices:["Oui, si besoin","Non, jamais","Oui, uniquement en zone verte","Oui, avec l'accord du manager"], answer:1},
  {cat:"Produits d'entretien", diff:"facile", q:"Quel produit sert au lavage et à la désinfection des mains ?", choices:["DrySan Oxy","KAY AMH Foam","Capital","Delimer"], answer:1},
  {cat:"Produits d'entretien", diff:"facile", q:"Peut-on remplir un vaporisateur destiné à un produit avec un autre produit ?", choices:["Oui, si les deux sont de la même marque","Non, c'est interdit","Oui, en cas de rupture de stock","Oui, en zone bleue uniquement"], answer:1},
  {cat:"Produits d'entretien", diff:"facile", q:"Que signifie le « T » du principe TACT ?", choices:["Temps d'application","Température de l'eau","Type de produit","Toxicité"], answer:1},
  {cat:"Produits d'entretien", diff:"facile", q:"Quel est l'objectif principal du nettoyage ?", choices:["Tuer les bactéries","Éliminer les résidus et souillures visibles","Désinfecter en profondeur","Parfumer la zone"], answer:1},
  {cat:"Produits d'entretien", diff:"facile", q:"Quel est l'objectif principal de la désinfection ?", choices:["Éliminer les résidus visibles","Éliminer les micro-organismes","Faire briller les surfaces","Éliminer les odeurs"], answer:1},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Quel produit est utilisé pour le dégraissage cuisine (friteuse, hottes) ?", choices:["KAY LiquidSense Heavy Duty Degreaser","KAY 5 Sanitizer","Capital Multipurpose","DrySan Oxy"], answer:0},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Quel produit est utilisé pour le détartrage des combinés shake/softy ?", choices:["KAY Delimer","KAY Fryer Cleanser","Bio-Shield","Kay 5"], answer:0},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Le DrySan Oxy s'utilise principalement pour quel usage ?", choices:["Nettoyant désinfectant avec rinçage obligatoire","Nettoyant désinfectant sans rinçage","Détartrant pour steamer","Dégraissant extérieur"], answer:1},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Combien de temps d'application faut-il respecter pour le Kay 5 (désinfection approfondie) ?", choices:["1 minute","5 minutes","10 minutes","15 minutes"], answer:2},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Quel produit sert à nettoyer la cuve des friteuses (poudre à récurer) ?", choices:["KAY Fryer Cleanser","Capital Multipurpose","DrySan Oxy","Kay 5"], answer:0},
  {cat:"Produits d'entretien", diff:"moyenne", q:"Quelles lettres composent le principe TACT dans l'ordre ?", choices:["Température, Action, Concentration, Temps","Temps, Action, Contrôle, Traçabilité","Type, Application, Concentration, Température","Température, Application, Contrôle, Temps"], answer:0},
  {cat:"Produits d'entretien", diff:"difficile", q:"Combien de tablettes KAY 5 Sanitizer faut-il pour 10 litres d'eau tiède ?", choices:["1 tablette","2 tablettes","3 tablettes","5 tablettes"], answer:0},
  {cat:"Produits d'entretien", diff:"difficile", q:"Quel dosage pour le Capital Multipurpose Concentrate en plonge manuelle (bac de 40 litres) ?", choices:["1 dose","2 doses","3 doses","4 doses"], answer:1},
  {cat:"Produits d'entretien", diff:"difficile", q:"Quelle est la fréquence d'utilisation des Eco-Clin Urinal Tablets par urinoir ?", choices:["1 fois par semaine","2 fois par semaine","1 fois par jour","2 fois par jour"], answer:1},

  // ===== SECURITE DES BIENS & DES PERSONNES =====
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Faut-il résister en cas de braquage ?", choices:["Oui, toujours","Non, jamais","Oui, si on est plusieurs","Seulement si le manager est présent"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Que doit-on faire en cas de brûlure ?", choices:["Appliquer de la glace directement","Faire ruisseler de l'eau froide","Appliquer une pommade immédiatement","Ne rien faire et attendre"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Quel numéro appeler pour les pompiers en France ?", choices:["15","17","18","114"], answer:2},
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Quel type de chaussures est obligatoire ?", choices:["Chaussures ouvertes","Chaussures de sécurité ou fermées avec semelles anti-dérapantes","Chaussures de ville","Peu importe le type"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Peut-on rester seul dans le restaurant à l'ouverture ou à la fermeture ?", choices:["Oui, sans problème","Non, jamais","Oui, si la porte est fermée","Oui, avec la vidéosurveillance"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"facile", q:"Doit-on ouvrir la porte à une tierce personne quand le restaurant est fermé à la clientèle ?", choices:["Oui, toujours","Non, jamais","Oui, si la personne est connue","Oui, en cas d'urgence uniquement"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Quel est le premier réflexe en cas de départ de feu sur une friteuse ?", choices:["Verser de l'eau","Appuyer sur le coup de poing cuisine","Évacuer immédiatement sans agir","Utiliser l'extincteur directement"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Comment doit-on soulever une charge lourde ?", choices:["En pliant le dos","En pliant les jambes, dos droit","En tournant le buste","Avec l'aide d'une seule main"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Comment faut-il déplacer les chariots (rolls) ?", choices:["Les pousser uniquement","Les tirer uniquement","Peu importe le sens","Les pousser ou les tirer selon la charge"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Que doit-on faire avant de nettoyer un équipement électrique ?", choices:["Le nettoyer directement à chaud","Le débrancher et le laisser refroidir minimum 15 minutes","Baisser simplement la puissance","Le nettoyer avec les mains mouillées"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Quel équipement de protection est obligatoire lors du filtrage des huiles à chaud ?", choices:["Uniquement des gants","Gants et lunettes de sécurité","Uniquement des lunettes","Aucun équipement nécessaire"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"moyenne", q:"Que doit-on faire en cas de coupure superficielle ?", choices:["Laisser à l'air libre","Soigner avec une solution antiseptique et recouvrir d'un pansement/doigtier","Continuer le travail normalement","Rincer à l'eau chaude uniquement"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"difficile", q:"Quelle est la durée maximale de travail quotidien pour un mineur ?", choices:["6 heures","7 heures","8 heures","10 heures"], answer:2},
  {cat:"Sécurité des biens & des personnes", diff:"difficile", q:"Combien de temps de pause obligatoire dès 4,5 heures de travail consécutif pour une femme enceinte (à compter du 4ème mois précédent l'accouchement) ?", choices:["10 minutes","15 minutes","20 minutes","30 minutes"], answer:1},
  {cat:"Sécurité des biens & des personnes", diff:"difficile", q:"Dans quel ordre doit-on intervenir en cas de feu de friteuse ?", choices:["Extincteur, coup de poing, couvercles","Coup de poing, couvercles, extincteur si besoin","Couvercles, coup de poing, extincteur","Évacuation, coup de poing, extincteur"], answer:1},

  // ===== ACCUEIL & SERVICE CLIENT =====
  {cat:"Accueil & service client", diff:"facile", q:"Que signifie l'acronyme BRASMA ?", choices:["Une méthode de vente","Les étapes de l'accueil client (Bonjour, Regard, Attention, Sourire, Merci, Au revoir)","Un protocole d'hygiène","Le nom d'un logiciel de caisse"], answer:1},
  {cat:"Accueil & service client", diff:"facile", q:"Combien de clients insatisfaits reviennent-ils en moyenne si le problème est résolu sur-le-champ ?", choices:["50%","70%","85%","95%"], answer:3},
  {cat:"Accueil & service client", diff:"facile", q:"Quel pourcentage de clients insatisfaits se manifeste réellement ?", choices:["4%","15%","25%","50%"], answer:0},
  {cat:"Accueil & service client", diff:"facile", q:"Que signifie VMV+ ?", choices:["Une méthode de nettoyage","Une méthode de vente (Vendre Mieux pour Vendre +)","Un logiciel de gestion","Un type de badge"], answer:1},
  {cat:"Accueil & service client", diff:"facile", q:"Faut-il toujours prévenir un client si un produit n'est pas immédiatement disponible ?", choices:["Non, jamais","Oui, toujours","Seulement si le manager le demande","Seulement en cas de rush"], answer:1},
  {cat:"Accueil & service client", diff:"facile", q:"Quelle formule est à bannir en caisse pour saluer un client ?", choices:["Bonjour Madame","Bonjour tout court","Bonjour Monsieur","Aucune, toutes sont correctes"], answer:1},
  {cat:"Accueil & service client", diff:"moyenne", q:"Que signifie SVP dans la méthode VMV+ ?", choices:["S'il Vous Plaît","Systématisation, Valorisation, Personnalisation","Service, Vente, Politesse","Sourire, Vitesse, Précision"], answer:1},
  {cat:"Accueil & service client", diff:"moyenne", q:"Dans l'ordre de service, qu'apporte-t-on en premier ?", choices:["Les frites","Les burgers","Serviettes et gobelet vide","Les desserts glacés"], answer:2},
  {cat:"Accueil & service client", diff:"moyenne", q:"Que signifie la méthode PERES pour gérer un retour client ?", choices:["Prendre en charge, Écouter, Reformuler, Exprimer son empathie, Suggérer une solution","Politesse, Écoute, Rapidité, Efficacité, Sourire","Prendre en charge, Évaluer, Réparer, Excuser, Servir","Un protocole de caisse"], answer:0},
  {cat:"Accueil & service client", diff:"moyenne", q:"Combien de temps maximum entre la prise en charge et la remise de la commande est visé ?", choices:["3 minutes","4min30","6 minutes","8 minutes"], answer:1},
  {cat:"Accueil & service client", diff:"moyenne", q:"Que doit-on toujours proposer systématiquement en caisse à 100% des clients ?", choices:["Uniquement une boisson","Le menu XL de la campagne, produit salé, sucré, café","Uniquement le dessert","Rien, sauf si le client demande"], answer:1},
  {cat:"Accueil & service client", diff:"moyenne", q:"Quelle formule est préférable à « Un café ? » pour maximiser la vente ?", choices:["Avec ceci ?","Un café court ou une boisson gourmande pour terminer votre repas ?","Pas de café ?","Ce sera tout ?"], answer:1},
  {cat:"Accueil & service client", diff:"difficile", q:"Sur combien de personnes en moyenne un client mécontent va-t-il témoigner de son insatisfaction ?", choices:["5 personnes","8 personnes","11 personnes","15 personnes"], answer:2},
  {cat:"Accueil & service client", diff:"difficile", q:"Dans l'ordre de service, à quelle étape se placent les frites et rustiques ?", choices:["1ère étape","2ème étape","3ème étape","4ème étape"], answer:2},
  {cat:"Accueil & service client", diff:"difficile", q:"Combien d'articles maximum recommandés par voyage pour optimiser le rassemblement d'une commande ?", choices:["2 produits","3 produits","4 produits","5 produits"], answer:1},

  // ===== PRODUCTION & EQUIPEMENTS =====
  {cat:"Production & équipements", diff:"facile", q:"Entre quelles températures à cœur doit se situer une viande de bœuf après cuisson ?", choices:["50°C à 60°C","69°C à 80°C","85°C à 95°C","40°C à 50°C"], answer:1},
  {cat:"Production & équipements", diff:"facile", q:"Quelle est la température cible à cœur pour un patty bœuf ?", choices:["65°C","70°C","75°C","80°C"], answer:2},
  {cat:"Production & équipements", diff:"facile", q:"Combien de temps un burger peut-il rester dans le bin (durée de conservation) ?", choices:["5 minutes","10 minutes","15 minutes","20 minutes"], answer:1},
  {cat:"Production & équipements", diff:"facile", q:"Quelle température minimum doit avoir un burger en fin de code dans le bin ?", choices:["45°C","52°C","60°C","65°C"], answer:1},
  {cat:"Production & équipements", diff:"facile", q:"Quelle température minimum pour des frites servies en fin de code ?", choices:["55°C","60°C","65°C","70°C"], answer:2},
  {cat:"Production & équipements", diff:"facile", q:"Que signifie l'apparition de spots rosés légèrement humides sur une viande cuite ?", choices:["La viande n'est pas cuite","C'est normal, la viande est cuite","Il faut la recuire","Un défaut de qualité"], answer:1},
  {cat:"Production & équipements", diff:"moyenne", q:"Quelle est la température de conservation d'une chambre froide négative ?", choices:["-5°C à -10°C","-18°C à -22°C","-25°C à -30°C","0°C à -5°C"], answer:1},
  {cat:"Production & équipements", diff:"moyenne", q:"Quelle est la température de conservation d'une chambre froide positive ?", choices:["+1°C à +4°C","+5°C à +8°C","-1°C à +1°C","+8°C à +12°C"], answer:0},
  {cat:"Production & équipements", diff:"moyenne", q:"Combien de temps de conservation pour du fingerfood dans le bin ?", choices:["5 minutes","10 minutes","15 minutes","20 minutes"], answer:1},
  {cat:"Production & équipements", diff:"moyenne", q:"Quelle température de l'huile de friture est programmée sur les friteuses frites/fingerfood ?", choices:["165°C","175°C","185°C","195°C"], answer:1},
  {cat:"Production & équipements", diff:"moyenne", q:"Quel est le temps de cuisson d'un patty Standard sur grill Garland en série ET (grande quantité) ?", choices:["38 secondes","48 secondes","58 secondes","68 secondes"], answer:1},
  {cat:"Production & équipements", diff:"moyenne", q:"Quelle est la capacité maximale de production de burgers à base de patties frits (poulet/poisson), tous types de cuisine confondus ?", choices:["2","3","4","6"], answer:2},
  {cat:"Production & équipements", diff:"difficile", q:"Quelle est la durée de conservation d'un fondant au chocolat dans le bin, en fin de code ?", choices:["15 minutes","20 minutes","30 minutes","45 minutes"], answer:2},
  {cat:"Production & équipements", diff:"difficile", q:"Quel est le temps de cuisson des churros en friteuse (en minutes) ?", choices:["1min50","2min10","2min30","2min50"], answer:1},
  {cat:"Production & équipements", diff:"difficile", q:"Combien de patties Medium maximum peuvent être cuits simultanément sur un grill Taylor (rabat court, série ET) ?", choices:["4","6","8","10"], answer:2},

  // ===== CULTURE QUICK & GLOSSAIRE =====
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Que signifie « Bin » chez Quick ?", choices:["Une poubelle","Le présentoir chauffant où sont placés les burgers","Un type de sauce","Un logiciel de caisse"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Que signifie « Rush » ?", choices:["Une pause","Une période d'affluence","Un type de nettoyage","Un poste de travail"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Que veut dire « VAE » ?", choices:["Vente À Emporter","Vérification Alimentaire Étendue","Vente Alimentaire Express","Vaisselle À Entretenir"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Que veut dire « SP » ?", choices:["Sécurité Produit","Service Personnalisé","Sur Place","Standard Process"], answer:2},
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Qu'est-ce qu'un « Patty » ?", choices:["Un type de pain","Un steak de viande hachée","Une sauce","Un ustensile de cuisine"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"facile", q:"Que signifie « Take Out » / « Take Away » ?", choices:["Vente sur place","Vente à emporter","Un poste de plonge","Une pause repas"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Qu'est-ce que le « Holding cabinet » ?", choices:["Un local à poubelles","Une armoire chauffante pour conserver les produits avant utilisation","Un système de caisse","Un vestiaire"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Que veut dire « MEP » ?", choices:["Mise En Poste","Mise En Place","Méthode d'Exploitation Produit","Matériel et Équipement Propre"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Qu'est-ce qu'un « Food Test » ?", choices:["Un contrôle qualité par dégustation d'un produit fini","Un test d'allergie","Un examen théorique du personnel","Un test de température ambiante"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Que signifie « LAD » ?", choices:["Livraison À Domicile","Local d'Approvisionnement Direct","Lavage Automatique des Denrées","Ligne d'Assemblage Directe"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Qu'est-ce qu'un « Gun » en cuisine Quick ?", choices:["Un type de patty","Le pistolet de distribution des sauces","Un équipement de nettoyage","Un synonyme de bin"], answer:1},
  {cat:"Culture Quick & glossaire", diff:"moyenne", q:"Que signifie « QSP » ?", choices:["Qualité Service Propreté","Quick Service Performance","Qualité Sécurité Personnel","Quick Standard Process"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"difficile", q:"Qu'est-ce qu'une « Tracel » ?", choices:["Une lavette tissu jetable, utilisée selon un code couleur","Un type de sauce","Un logiciel de traçabilité","Un ustensile de découpe"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"difficile", q:"Que signifie « MMM » chez Quick ?", choices:["Menu Mix Management","Mode de Maintenance du Matériel","Manuel des Méthodes Maison","Marge Moyenne Mensuelle"], answer:0},
  {cat:"Culture Quick & glossaire", diff:"difficile", q:"Qu'est-ce que le « Strike Rate » ?", choices:["Le taux de rupture de stock","Le taux de vente d'un produit sur 100 tickets","Le taux de satisfaction client","Le taux d'erreur en caisse"], answer:1}
];

// ===== BANQUE BLUR-GER =====
// Chaque produit : nom affiché, dossier, liste des fichiers images disponibles (variantes), famille (pour les leurres)
const BLURGER_PRODUCTS = [
  // BURGERS
  {name:"Giant", folder:"Burgers", files:["Giant.png"], family:"burgers"},
  {name:"RMQ Cesar", folder:"Burgers", files:["RMQ-Cesar.png"], family:"burgers"},
  {name:"Cheeseburger", folder:"Burgers", files:["cheeseburger.png"], family:"burgers"},
  {name:"Classiq Crispy Onions Chicken", folder:"Burgers", files:["classiq crispy onions chicken.png"], family:"burgers"},
  {name:"Double Cheese", folder:"Burgers", files:["double cheese.png"], family:"burgers"},
  {name:"Giant Max", folder:"Burgers", files:["giant max.png"], family:"burgers"},
  {name:"Giant Mega", folder:"Burgers", files:["giant mega.png"], family:"burgers"},
  {name:"Giga Giant", folder:"Burgers", files:["giga-giant.png"], family:"burgers"},
  {name:"Hamburger", folder:"Burgers", files:["hamburger.png"], family:"burgers"},
  {name:"Long Bacon", folder:"Burgers", files:["long bacon.png"], family:"burgers"},
  {name:"Long Chicken", folder:"Burgers", files:["long chicken.png"], family:"burgers"},
  {name:"Long Fish", folder:"Burgers", files:["long fish.png"], family:"burgers"},
  {name:"Qarrement Boeuf", folder:"Burgers", files:["qarrement boeuf.png"], family:"burgers"},
  {name:"Qarrement Poulet", folder:"Burgers", files:["qarrement poulet.png"], family:"burgers"},
  {name:"QNT", folder:"Burgers", files:["qnt.png"], family:"burgers"},
  {name:"Suprême Bacon", folder:"Burgers", files:["supreme bacon.png"], family:"burgers"},
  {name:"Suprême Classiq", folder:"Burgers", files:["supreme classiq.png"], family:"burgers"},
  {name:"Suprême Spicy Chicken", folder:"Burgers", files:["supreme spicy chicken.png"], family:"burgers"},
  {name:"Wrap Veggie", folder:"Burgers", files:["wrap veggie.png"], family:"burgers"},
  {name:"Xtra Long Bacon", folder:"Burgers", files:["xtra-long-bacon.png"], family:"burgers"},
  {name:"Xtra Long Chicken", folder:"Burgers", files:["xtra-long-chicken.png"], family:"burgers"},
  {name:"Xtra Long Onion", folder:"Burgers", files:["xtra-long-onion.png"], family:"burgers"},

  // DESSERTS (avec fusion des doublons de quantité)
  {name:"Bigoût Choco", folder:"Desserts", files:["bigout choco.png"], family:"desserts"},
  {name:"Churros", folder:"Desserts", files:["churros 10.png","churros 5.png"], family:"desserts_churros"},
  {name:"Churros Kitkat", folder:"Desserts", files:["churros kitkat 10.png","churros kitkat 5.png"], family:"desserts_churros"},
  {name:"Cœur de Beignets", folder:"Desserts", files:["coeur de beignets.png"], family:"desserts"},
  {name:"Compote", folder:"Desserts", files:["compote.png"], family:"desserts"},
  {name:"Cookie Trio Choco", folder:"Desserts", files:["cookie trio choco.png"], family:"desserts"},
  {name:"Cornet Vanille", folder:"Desserts", files:["cornet vanille.png"], family:"desserts"},
  {name:"Funny Fruit", folder:"Desserts", files:["funny fruit.png"], family:"desserts"},
  {name:"Magnum Mini Amande", folder:"Desserts", files:["magnum mini amande.png"], family:"desserts"},
  {name:"Mini Yop Fraise", folder:"Desserts", files:["mini yop fraise.png"], family:"desserts"},
  {name:"Mix Mania Kitkat", folder:"Desserts", files:["mix mania kitkat.png"], family:"desserts_mixmania"},
  {name:"Mix Mania M&M's", folder:"Desserts", files:["mix mania mms.png"], family:"desserts_mixmania"},
  {name:"Mix Mania Snickers", folder:"Desserts", files:["mix mania snickers.png"], family:"desserts_mixmania"},
  {name:"Qarre Donut", folder:"Desserts", files:["qarre donut.png"], family:"desserts"},
  {name:"Shake Caramel", folder:"Desserts", files:["shake caramel.png"], family:"desserts_shake"},
  {name:"Shake Chocolat", folder:"Desserts", files:["shake chocolat.png"], family:"desserts_shake"},
  {name:"Shake Fraise", folder:"Desserts", files:["shake fraise.png"], family:"desserts_shake"},
  {name:"Shake Vanille", folder:"Desserts", files:["shake vanille.png"], family:"desserts_shake"},
  {name:"Shake Gourmand Caramel", folder:"Desserts", files:["shake gourmand caramel.png"], family:"desserts_shakegourmand"},
  {name:"Shake Gourmand Chocolat", folder:"Desserts", files:["shake gourmand chocolat.png"], family:"desserts_shakegourmand"},
  {name:"Shake Gourmand Fraise", folder:"Desserts", files:["shake gourmand fraise.png"], family:"desserts_shakegourmand"},
  {name:"Shake Gourmand Vanille", folder:"Desserts", files:["shake gourmand vanille.png"], family:"desserts_shakegourmand"},
  {name:"Softy Caramel", folder:"Desserts", files:["softy caramel.png"], family:"desserts_softy"},
  {name:"Softy Chocolat", folder:"Desserts", files:["softy chocolat.png"], family:"desserts_softy"},
  {name:"Softy Fraise", folder:"Desserts", files:["softy fraise.png"], family:"desserts_softy"},
  {name:"Softy Nature", folder:"Desserts", files:["softy nature.png"], family:"desserts_softy"},
  {name:"Softy Gourmand Caramel", folder:"Desserts", files:["softy gourmand caramel.png"], family:"desserts_softygourmand"},
  {name:"Softy Gourmand Chocolat", folder:"Desserts", files:["softy gourmand chocolat.png"], family:"desserts_softygourmand"},
  {name:"Softy Gourmand Fraise", folder:"Desserts", files:["softy gourmand fraise.png"], family:"desserts_softygourmand"},

  // FINGER FOODS (avec fusion des doublons de quantité)
  {name:"Cheesy Rolls", folder:"Finger Foods", files:["cheesy rolls 10.png","cheesy rolls 3.png"], family:"fingerfood"},
  {name:"Chicken Dips", folder:"Finger Foods", files:["chicken dips 20.png","chicken dips 4.png","chicken dips 7.png"], family:"fingerfood"},
  {name:"Chicken Wings", folder:"Finger Foods", files:["chicken wings 5.png"], family:"fingerfood"},
  {name:"Onion Rings", folder:"Finger Foods", files:["onion rings 5.png","onion rings 9.png"], family:"fingerfood"},
  {name:"Quickbox Cheesy Rolls", folder:"Finger Foods", files:["quickbox cheesy rolls.png"], family:"fingerfood"},

  // SALADES
  {name:"Cup Kiri", folder:"Salades", files:["cup kiri.png"], family:"salades"},
  {name:"Petite Salade", folder:"Salades", files:["petite salade.png"], family:"salades"},
  {name:"Salade Cheesy Rolls", folder:"Salades", files:["salade cheesy rolls.png"], family:"salades"},
  {name:"Salade Chicken", folder:"Salades", files:["salade chicken.png"], family:"salades"},
  {name:"Salade Veggie", folder:"Salades", files:["salade veggie.png"], family:"salades"},
  {name:"Tomates", folder:"Salades", files:["tomatoes 5.png"], family:"salades"},

  // SAUCES
  {name:"Sauce Barbecue", folder:"Sauces", files:["sauce barbecue.png"], family:"sauces"},
  {name:"Sauce Curry", folder:"Sauces", files:["sauce curry.png"], family:"sauces"},
  {name:"Sauce Fromage Blanc Ciboulette", folder:"Sauces", files:["sauce fromage blanc ciboulette.png"], family:"sauces"},
  {name:"Sauce Fromagère Tomate Basilic", folder:"Sauces", files:["sauce fromagere tomate basilic.png"], family:"sauces"},
  {name:"Sauce Giant XXL", folder:"Sauces", files:["sauce giant xxl.png"], family:"sauces"},
  {name:"Sauce Giant", folder:"Sauces", files:["sauce giant.png"], family:"sauces"},
  {name:"Sauce Hot Salsa", folder:"Sauces", files:["sauce hot salsa.png"], family:"sauces"},
  {name:"Sauce Ketchup", folder:"Sauces", files:["sauce ketchup.png"], family:"sauces"},
  {name:"Sauce Long Bacon", folder:"Sauces", files:["sauce long bacon.png"], family:"sauces"},
  {name:"Sauce Mayonnaise", folder:"Sauces", files:["sauce mayonnaise.png"], family:"sauces"},
  {name:"Sauce QNT", folder:"Sauces", files:["sauce qnt.png"], family:"sauces"},
  {name:"Sauce Suprême Spicy", folder:"Sauces", files:["sauce supreme spicy.png"], family:"sauces"},
  {name:"Sauce Tartare", folder:"Sauces", files:["sauce tartare.png"], family:"sauces"},
  {name:"Sauce Vinaigre Balsamique", folder:"Sauces", files:["sauce vinaigre balsamique.png"], family:"sauces"}
];
